### ISSUE TITLE
Titulo del proyecto

### ISSUE THREAD

**Issue by DrJoseGallardo** [Margarita3048/MargaritaRivera#1]
Estimada Margarita, Aquí le dejo mis sugerencias a su proyecto:

1.- El titulo no es informativo pues incluye un elemento que no se analizará - la expresión de genes. Le sugiero remover ese elemento.

2.- En su resumen del problema, ¿es correcto indicar que la cepa está patentada?. ¿Tiene el numero de la patente? ¿Cuál es su referencia para indicar que está patentada.?

3.- La estructura de redacción del primer parrafo es inadecuada. Recuerde que un párrafo se estructura como frase de inicio, frases de desarrollo y cierre. Usted abre el párrafo indicando que la cepa se cultiva en Chile y esta patentada, eso indica que el resto del párrafo usted profundizará en esa información. Al contrario, usted nunca menciona evidencias de que esté patentada. Por otra parte, en una sola oración muy larga plantea el problema de maduración de la cepa, algo que no está en la frase de inicio. 

4.- La estructura del segundo párrafo es inadecuada por la misma razón anterior. la frase de inicio plantea que dado el problema de maduración es importante "en condiciones de engorda" y que se "es necesario optar por nuevas estrategias de control", no menciona a la cepa. Luego uno espera que profundice y desarrolle ambos elementos. En cambio, el parrafo continua con 2 oraciones habla un poco sin entregar detalles de alguna relacione entre genetica y maduracion primero en peces silvestres y domesticados y luego en la cepa, en el contexto de seleccion genomica.

5.- El tercer párrafo es una sola oración, por lo que nuevamente es inadecuada.

6.- No se entiende cual es el problema que desea resolver "con los datos disponibles".

7.- Le sugiero que plantee como problema que existen peces que maduran temprano y otros de manera tardia y que usted desea comparar el nivel de maduración medido como IGS y otras variables morfometricas.

**Comment by Margarita3048** [comment]
Muchas gracias por las recomendaciones Profe. Corregiré lo indicado.

**Comment by Margarita3048** [comment]
Buenas tardes profesor en relación, a sus recomendaciones respondo y le consulto a continuación:

1.- El titulo no es informativo pues incluye un elemento que no se analizará - la expresión de genes. Le sugiero remover ese elemento.

Dr., coincido con usted y he modificado el título por otro que explica mejor a que se enfoca mi análisis exploratorio, por favor si cree usted que este título es más adecuado, le agradezco me lo haga saber. Gracias.

"Análisis exploratorio de variables morfométricas y productivas asociadas a la edad de maduración en machos de la cepa Lochy de _Salmo salar_"

2.- En su resumen del problema, ¿es correcto indicar que la cepa está patentada?. ¿Tiene el numero de la patente? ¿Cuál es su referencia para indicar que está patentada.?

Profesor, mi confusión surgió por la información que se expone en la hoja 6 del siguiente reporte de sostenibilidad de la empresa Salmones Camanchaca, donde no estoy segura de si hice una traducción adecuada de la palabra "proprietary". En todo caso, al no estar segura de esto, procedí a descartar esta información y coloqué únicamente que la cepa se cultiva por dicha empresa en Chile, pues dezconozco también el número de patente.

https://salmonescamanchaca.cl/wp-content/uploads/2020/09/SC-CMD-2019-Operations.pdf 

3.- La estructura de redacción del primer parrafo es inadecuada. Recuerde que un párrafo se estructura como frase de inicio, frases de desarrollo y cierre. Usted abre el párrafo indicando que la cepa se cultiva en Chile y esta patentada, eso indica que el resto del párrafo usted profundizará en esa información. Al contrario, usted nunca menciona evidencias de que esté patentada. Por otra parte, en una sola oración muy larga plantea el problema de maduración de la cepa, algo que no está en la frase de inicio.

Gracias por la recomendación profesor. He modificado el primer párrafo centrando la idea principal en la ventaja de crecimiento y desventaja en maduración que tiene la cepa. Haciendo memoria de la dificultad productiva del rasgo de la maduración adelantada en las pisciculturas

4.- La estructura del segundo párrafo es inadecuada por la misma razón anterior. la frase de inicio plantea que dado el problema de maduración es importante "en condiciones de engorda" y que se "es necesario optar por nuevas estrategias de control", no menciona a la cepa. Luego uno espera que profundice y desarrolle ambos elementos. En cambio, el parrafo continua con 2 oraciones habla un poco sin entregar detalles de alguna relacione entre genetica y maduracion primero en peces silvestres y domesticados y luego en la cepa, en el contexto de seleccion genomica.

He modificado el segundo párrafo centrando la idea principal en las estrategias de control y como este análisis exploratorio es una base para conocer el grado en el que varían algunas variables de acuerdo a sue stadío de maduración


5.- El tercer párrafo es una sola oración, por lo que nuevamente es inadecuada.

Elimine el tercer párrafo e hice solo una breve descripción y cierre del exploratorio. Aún así si es conveniente lo retiraré


6.- No se entiende cual es el problema que desea resolver 

Con la nueva redacción de los párrafos considero que he centrado de mejor manera el problema

**Comment by DrJoseGallardo** [comment]
Conforme con las mejoras del proyecto.
